<div class="container">
	<div class="row">
		<div class="span3 bs-docs-sidebar">
			<ul class="nav nav-list bs-docs-sidenav affix-top">
				<li>
					<a href="#overview">Overview</a>
				</li>
				<li>
					<a href="#application">Application</a>
				</li>
				<li>
					<a href="#controllers">Controllers</a>
				</li>
				<li>
					<a href="#models">Models</a>
				</li>
				<li>
					<a href="#views">Views</a>
				</li>
			</ul>
		</div>
		<div class="span9">
			<section id="overview">
				<div class="page-header">
					<h1>1. Overview</h1>					
				</div>
				<p class="lead">
					
				</p>
				<p>
					It's construction is based on the model, view, controller (MVC) pattern.  The goal  
				</p>
			</section>
			<section id="application">
				<div class="page-header">
					<h1>2. Application</h1>					
				</div>
				<p class="lead">
					
				</p>
				<p>
					
				</p>
			</section>
			<section id="controllers">
				<div class="page-header">
					<h1>3. Controllers</h1>
				</div>
				<p class="lead">
					
				</p>
			</section>
			<section id="models">
				<div class="page-header">
					<h1>4. Models</h1>
				</div>
				<p class="lead">
					
				</p>
			</section>
			<section id="views">
				<div class="page-header">
					<h1>5. Views</h1>
				</div>
				<p class="lead">
					
				</p>
			</section>
		</div>
	</div>
</div>